// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NameNodeRpcModel.proto

package com.shawnliang.github.dfs.namenode.rpc.model;

public interface HeartbeatResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.shawnliang.github.dfs.namenode.rpc.HeartbeatResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 status = 1;</code>
   */
  int getStatus();
}
