// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NameNodeRpcModel.proto

package com.shawnliang.github.dfs.namenode.rpc.model;

public final class NameNodeRpcModel {
  private NameNodeRpcModel() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_shawnliang_github_dfs_namenode_rpc_RegisterRequest_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_shawnliang_github_dfs_namenode_rpc_RegisterRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_shawnliang_github_dfs_namenode_rpc_RegisterResponse_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_shawnliang_github_dfs_namenode_rpc_RegisterResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_shawnliang_github_dfs_namenode_rpc_HeartbeatRequest_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_shawnliang_github_dfs_namenode_rpc_HeartbeatRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_shawnliang_github_dfs_namenode_rpc_HeartbeatResponse_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_shawnliang_github_dfs_namenode_rpc_HeartbeatResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_shawnliang_github_dfs_namenode_rpc_MkdirRequest_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_shawnliang_github_dfs_namenode_rpc_MkdirRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_shawnliang_github_dfs_namenode_rpc_MkdirResponse_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_shawnliang_github_dfs_namenode_rpc_MkdirResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\026NameNodeRpcModel.proto\022&com.shawnliang" +
      ".github.dfs.namenode.rpc\"/\n\017RegisterRequ" +
      "est\022\n\n\002ip\030\001 \001(\t\022\020\n\010hostname\030\002 \001(\t\"\"\n\020Reg" +
      "isterResponse\022\016\n\006status\030\001 \001(\005\"0\n\020Heartbe" +
      "atRequest\022\n\n\002ip\030\001 \001(\t\022\020\n\010hostname\030\002 \001(\t\"" +
      "#\n\021HeartbeatResponse\022\016\n\006status\030\001 \001(\005\"\034\n\014" +
      "MkdirRequest\022\014\n\004path\030\001 \001(\t\"\037\n\rMkdirRespo" +
      "nse\022\016\n\006status\030\001 \001(\005BB\n,com.shawnliang.gi" +
      "thub.dfs.namenode.rpc.modelB\020NameNodeRpc" +
      "ModelP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_shawnliang_github_dfs_namenode_rpc_RegisterRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_shawnliang_github_dfs_namenode_rpc_RegisterRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_shawnliang_github_dfs_namenode_rpc_RegisterRequest_descriptor,
        new String[] { "Ip", "Hostname", });
    internal_static_com_shawnliang_github_dfs_namenode_rpc_RegisterResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_shawnliang_github_dfs_namenode_rpc_RegisterResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_shawnliang_github_dfs_namenode_rpc_RegisterResponse_descriptor,
        new String[] { "Status", });
    internal_static_com_shawnliang_github_dfs_namenode_rpc_HeartbeatRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_shawnliang_github_dfs_namenode_rpc_HeartbeatRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_shawnliang_github_dfs_namenode_rpc_HeartbeatRequest_descriptor,
        new String[] { "Ip", "Hostname", });
    internal_static_com_shawnliang_github_dfs_namenode_rpc_HeartbeatResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_shawnliang_github_dfs_namenode_rpc_HeartbeatResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_shawnliang_github_dfs_namenode_rpc_HeartbeatResponse_descriptor,
        new String[] { "Status", });
    internal_static_com_shawnliang_github_dfs_namenode_rpc_MkdirRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_shawnliang_github_dfs_namenode_rpc_MkdirRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_shawnliang_github_dfs_namenode_rpc_MkdirRequest_descriptor,
        new String[] { "Path", });
    internal_static_com_shawnliang_github_dfs_namenode_rpc_MkdirResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_shawnliang_github_dfs_namenode_rpc_MkdirResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_shawnliang_github_dfs_namenode_rpc_MkdirResponse_descriptor,
        new String[] { "Status", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
