// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NameNodeRpcServer.proto

package com.shawnliang.github.dfs.namenode.rpc.service;

public final class NameNodeServer {
  private NameNodeServer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027NameNodeRpcServer.proto\022&com.shawnlian" +
      "g.github.dfs.namenode.rpc\032\026NameNodeRpcMo" +
      "del.proto2\223\002\n\017NameNodeService\022}\n\010registe" +
      "r\0227.com.shawnliang.github.dfs.namenode.r" +
      "pc.RegisterRequest\0328.com.shawnliang.gith" +
      "ub.dfs.namenode.rpc.RegisterResponse\022\200\001\n" +
      "\theartbeat\0228.com.shawnliang.github.dfs.n" +
      "amenode.rpc.HeartbeatRequest\0329.com.shawn" +
      "liang.github.dfs.namenode.rpc.HeartbeatR" +
      "esponseBB\n.com.shawnliang.github.dfs.nam" +
      "enode.rpc.serviceB\016NameNodeServerP\001b\006pro" +
      "to3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.shawnliang.github.dfs.namenode.rpc.model.NameNodeRpcModel.getDescriptor(),
        }, assigner);
    com.shawnliang.github.dfs.namenode.rpc.model.NameNodeRpcModel.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
